### ISSUE TITLE
"Cannot Connect" screen

### ISSUE THREAD

**Issue by luciorubeens** [ArkEcosystemArchive/payvo-wallet-issues#1]
### Describe the Bug

It displays an offline screen when connected, scrolling down displays the expected content. Clearing the site data and cache didn't fix it.

### Expected Behavior

Do not show offline screen

### To Reproduce

![CleanShot 2022-04-03 at 18 56 17](https://user-images.githubusercontent.com/4539235/161450628-d19b2b6d-f66e-4146-a58c-778687f43395.gif)

### What operating system are you using?

macOS

### What browser are you using?

Chrome

**Comment by dated** [comment]
Hi there @luciorubeens 👋🏻 can you have a look if the errors persists here https://payvo-wallet-991hr2v9i-arkecosystem.vercel.app/ ?

**Comment by dated** [comment]
If the Connection Error is still being displayed, please try turning your WiFi connection off and on again, this might be caused by a Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=678075

**Comment by luciorubeens** [comment]
@dated Looks good now, thank you! Btw great work you all, adios Electron! 😆
