### ISSUE TITLE
login & logout [Section] 

### ISSUE THREAD

**Issue by ghost** [ArkEcosystemArchive/payvo-wallet-issues#2]
### Describe the Bug

I created my account and went to test to import the ARK crypto asset, but I couldn't import it, because the wallet gives an error and disconnects all the time.

### Expected Behavior

manage to create the wallet

### To Reproduce

https://prnt.sc/l8JLiZlrH5Vf
https://prnt.sc/3CbbT099KOmV
https://prnt.sc/nHWID2jGeBu4

### What operating system are you using?

Windows

### What browser are you using?

Vivaldi

**Comment by samharperpittam** [comment]
Hello @tykocompany 

Thank you for reporting this issue to us. 

To help us recreate this issue, it would be excellent if you could provide the following pieces of information:

1) Vivaldi version number you have installed
2) Take a screenshot of any errors that appear in your browser console log when you attempt to create a wallet and see the "Something went wrong" page.  
(You can access the console log by opening developer tools with keyboard shortcut Ctrl+Shift+J)

_*Note: Please do not use the mnemonic that was posted in your screenshots above as it is no longer secure*_
